services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: xcfe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./infra/db.sql:/docker-entrypoint-initdb.d/00-db.sql:ro

  adminer:
    image: adminer:4
    restart: unless-stopped
    ports:
      - '8081:8080'
    depends_on:
      - db

volumes:
  pgdata:
